[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-zope.i18nmessageid",
	"source": "zope.i18nmessageid",
	"version": "4.0.3-2build4",
	"section": "universe/zope",
	"priority": "extra",
	"architecture": "amd64",
	"depends": [
		"python3 (<< 3.7)",
		"python3 (>= 3.6~)",
		"python3-pkg-resources",
		"python3:any (>= 3.3.2-2~)",
		"libc6 (>= 2.4)"
	],
	"conflicts": [
		"zope3"
	],
	"installedSize": 55,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "Message Identifiers for internationalization",
	"homepage": "http://pypi.python.org/pypi/zope.i18nmessageid",
	"filename": "pool/universe/z/zope.i18nmessageid/python3-zope.i18nmessageid_4.0.3-2build4_amd64.deb",
	"size": 11586,
	"md5": "3eb9f1d282a585a0c3d762524a8ae13c",
	"sha1": "91b5b163970498e3a1371b466c223048b6bdc393",
	"sha256": "2df00e67d701f20e459b7214d268cca9727adacca4833a15551b6a07cc9b2633",
	"descriptionMd5": "a4ecc20de96c439e99b9eec842e6110b"
}]