[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-requestsexceptions",
	"source": "python-requestsexceptions",
	"version": "1.3.0-3",
	"section": "universe/python",
	"priority": "extra",
	"architecture": "all",
	"depends": [
		"python3-pbr (>= 2.0.0)",
		"python3-urllib3 (>= 1.13)",
		"python3:any (>= 3.3.2-2~)"
	],
	"installedSize": 23,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "import exceptions from bundled packages in requests. - Python 3.x",
	"homepage": "http://www.openstack.org/",
	"filename": "pool/universe/p/python-requestsexceptions/python3-requestsexceptions_1.3.0-3_all.deb",
	"size": 4116,
	"md5": "6dfa8fdaea6d60f17f35278acee66078",
	"sha1": "b2fce67f08e950a02c7769ea4714ac73bece2337",
	"sha256": "d21e04ff68c48b4d8eec2c9d747774014a398f88e739d55b719a10e65e9ff4ab",
	"descriptionMd5": "69eb6ceafcc256efdfb4eb0d4dce11c3"
}]