[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python-zope.i18nmessageid",
	"source": "zope.i18nmessageid",
	"version": "4.0.3-2build4",
	"section": "universe/python",
	"priority": "extra",
	"architecture": "amd64",
	"depends": [
		"python (<< 2.8)",
		"python (>= 2.7~)",
		"python-pkg-resources",
		"python:any (<< 2.8)",
		"python:any (>= 2.7.5-5~)",
		"libc6 (>= 2.4)"
	],
	"conflicts": [
		"zope3"
	],
	"installedSize": 58,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "Message Identifiers for internationalization",
	"homepage": "http://pypi.python.org/pypi/zope.i18nmessageid",
	"filename": "pool/universe/z/zope.i18nmessageid/python-zope.i18nmessageid_4.0.3-2build4_amd64.deb",
	"size": 11470,
	"md5": "adaa82d6ba1a895fc7f5a14e5ffd3545",
	"sha1": "c21e4a326efed4a5574e60648b8c11fe936dd683",
	"sha256": "a5c4ffec1f79dac4fbad65704f1026e8d53df4ab1ff10fc48933a903178ead24",
	"descriptionMd5": "4484ca5e9a74d928f306c3f4c34308f5"
}]