[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-parso",
	"source": "parso",
	"version": "0.8.4-1",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3:any"
	],
	"installedSize": 368,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "Python parser that supports error recovery - Python 3.X",
	"homepage": "https://github.com/davidhalter/parso",
	"filename": "pool/universe/p/parso/python3-parso_0.8.4-1_all.deb",
	"size": 67646,
	"md5": "7ae2af8ca174c97cb2cb54975488ee4e",
	"sha1": "7150ff5e55caf12f1447e62307b1a5b565ab679e",
	"sha256": "52072392d420daf87e66548765c0769dc37b0ab0912c068c1e51e056b89d02b0",
	"sha512": "4737efbeccea5e8c2f497e9e6cf710b8b36893d8ad3185912d75dd3991276af3ec0fe6addf1ce167a6e8f321233ccf67ffada4f39e0c97ec35b52fb335971257",
	"descriptionMd5": "e635c0ee32596f7972cf7149e68ca563"
}]