{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pytest-check",
	"source": "pytest-check",
	"version": "2.3.0-1",
	"section": "universe/python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-pytest",
		"python3:any"
	],
	"installedSize": 90,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "Pytest plugin that allows multiple failures per test (Python 3)",
	"homepage": "https://github.com/okken/pytest-check",
	"filename": "pool/universe/p/pytest-check/python3-pytest-check_2.3.0-1_all.deb",
	"size": 16764,
	"md5": "3959ae4debf258fe6b063732fc8a5cf8",
	"sha1": "6a7c6d0536aa530e308868f1f5725530165bad15",
	"sha256": "25594cc354ca065a9b90079561e9d424e06158f97e0d8c80368050e66635c287",
	"sha512": "1d3804959dfce8dea26abbc02308160cb097cccebee1060bb9a0eef16e602993e2189665b3fcda517da46d799fc001d1aeb501fe835006a2ff3561fe3220b414",
	"descriptionMd5": "d26f0d874a55ca972f407eb780a2379f"
}