{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python-pytest-instafail-doc",
	"source": "pytest-instafail",
	"version": "0.1.0-1",
	"section": "universe/doc",
	"priority": "optional",
	"architecture": "all",
	"installedSize": 37,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "plugin for py.test that shows failures and errors instantly",
	"homepage": "https://pypi.python.org/pypi/pytest-instafail",
	"filename": "pool/universe/p/pytest-instafail/python-pytest-instafail-doc_0.1.0-1_all.deb",
	"size": 5134,
	"md5": "e794d0e9df6253ae4b2e5614120ce838",
	"sha1": "a0033bcc7654bdb6e35045850b9dbe8c7ee4cae8",
	"sha256": "d6e171e2dceb27e9e4b908fccb9c6d25bde7b55203de7cc76f6c05878869e07e",
	"descriptionMd5": "1a83ab133282a9806a57ee198e282902"
}