{"raw":{},"required":["Filename","Size"],"package":"python-zope.error","source":"zope.error","version":"3.7.2-0ubuntu4","section":"universe/zope","priority":"extra","architecture":"all","depends":["python-pkg-resources","python-zodb","python-zope","python-zope.exceptions","python-zope.interface","python-zope.location","python2.7","python (>= 2.7.1-0ubuntu2)","python (<< 2.8)"],"suggests":["python-zope.testing"],"installedSize":97,"maintainer":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","description":"Error reporting utility for Zope","filename":"pool/universe/z/zope.error/python-zope.error_3.7.2-0ubuntu4_all.deb","size":10404,"md5":"8d408c7eca31c347f113434fb4542724","sha1":"a29d6683eac9f1c265cf3b4ee39497bb2a29e482","sha256":"f7f47d77395b569b43cfaef07ce4b27c9e993a0e20a575a6118992a2cdc34608","descriptionMd5":"a0fdd54dd3b5ec3becb6d68af3983f37"}