{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python-zdaemon",
	"source": "zdaemon",
	"version": "2.0.7-1",
	"section": "universe/python",
	"priority": "extra",
	"architecture": "all",
	"depends": [
		"python2.7",
		"python (>= 2.7.1-0ubuntu2)",
		"python (<< 2.8)",
		"python-zconfig",
		"python-pkg-resources"
	],
	"conflicts": [
		"zope3"
	],
	"installedSize": 238,
	"maintainer": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
	"description": "daemon process control library and tools for Unix-based systems",
	"homepage": "http://pypi.python.org/pypi/zdaemon",
	"filename": "pool/universe/z/zdaemon/python-zdaemon_2.0.7-1_all.deb",
	"size": 49938,
	"md5": "182dfd3a35e4bfc5f1811f4934857521",
	"sha1": "a458d1550603d2b160351abd70a8758eac132992",
	"sha256": "21864464940185ea9dab0588e0ba96f708be41c7a5758bb88cf2e1766efd2276",
	"descriptionMd5": "761f8913e1ddea787af8398012cd07d6"
}